#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again. This script gets executed directly, so it could be python, php,
# ruby, etc.

function bundle_install() {
  if [ ! -d "${OPENSHIFT_REPO_DIR}/.bundle" ] && [ -f "${OPENSHIFT_REPO_DIR}/Gemfile" ]; then
    pushd ${OPENSHIFT_REPO_DIR} > /dev/null
    jruby -J-Xmx256m -J-Dhttps.protocols=SSLv3 -S bundle install --without development test --deployment
    popd > /dev/null
  fi
}
